site_name: Python SDK Documentation

theme:
  name: "material"
  logo: "assets/images/logo.svg"

extra:
  generator: false

copyright: Copyright &copy; 2026 PDFGate.com

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference: reference.md
